client_config_file: ./credentials/credentials.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: ./credentials/tokens.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.metadata